-- V1: baseline.
--
-- This reproduces, by hand, the table that Hibernate used to generate for you from
-- SoftwareEngineer.java when ddl-auto was set to create-drop. Nothing new is being
-- added here; the point is to move ownership of the schema from Hibernate to Flyway.
--
-- Filename format matters and is not decoration:
--   V        = a versioned migration (runs once, in order)
--   1        = the version number
--   __       = TWO underscores separating version from description
--   create_software_engineer = description, shown in the flyway_schema_history table
--
-- THE RULE THAT MAKES MIGRATIONS WORK: once a V file has run anywhere other than
-- your own machine, you never edit it again. Flyway stores a checksum of each file
-- in flyway_schema_history and refuses to start if a file it already applied has
-- changed. To alter this table later you add V3, V4, ... You do not rewrite history.
-- That constraint is the entire reason a real database can be evolved safely.

CREATE TABLE software_engineer
(
    -- GENERATED BY DEFAULT AS IDENTITY is the modern SQL-standard equivalent of
    -- `serial`, and it is what Hibernate's GenerationType.IDENTITY expects here.
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(255),
    tech_stack VARCHAR(255),
    CONSTRAINT pk_software_engineer PRIMARY KEY (id)
);

-- Note how the Java field `techStack` became the column `tech_stack`. You never
-- configured that. Hibernate's default naming strategy converts camelCase to
-- snake_case, which is why `validate` will accept this table as a match for the
-- entity. Name the column `techStack` instead and startup fails - try it once.
